spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: ppxoj-backend-user-service
          uri: lb://ppxoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: ppxoj-backend-question-service
          uri: lb://ppxoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: ppxoj-backend-judge-service
          uri: lb://ppxoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: ppxoj-backend-gateway
  main:
    web-application-type: reactive
server:
  # 网关一般定义为1结尾的端口
  port: 8101
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式,自动从上面发现网关下的所有子服务
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2

